[package]
name = "allowit-vault"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
build = "../../policy/build.rs"
[lib]
crate-type = ["cdylib"]
[features]
no-entrypoint = []
stellar = []
[dependencies]
solana-program.workspace = true
borsh.workspace = true
allowit-interface.workspace = true
spl-token = { version = "=8.0.0", features = ["no-entrypoint"] }
[lints.rust]
unexpected_cfgs = { level = "allow" }

[build-dependencies]
sha2 = "=0.10.9"
