[package]
name = "allowit-paysh"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
[lib]
crate-type = ["cdylib"]
[features]
no-entrypoint = []
[dependencies]
solana-program.workspace = true
borsh.workspace = true
allowit-paysh-interface = { path = "../../crates/paysh-interface" }
spl-token = { version = "=8.0.0", features = ["no-entrypoint"] }
[lints.rust]
unexpected_cfgs = { level = "allow" }
